### ISSUE TITLE
Discussion of new major version

### ISSUE THREAD

**Issue by ghedipunk** [ghedipunk/PHP-Websockets#14]
Based on maturing as a developer, I feel that there are some fundamental architectural changes to the project that would benefit other developers and projects.

While the current implementation is technically sound, and can easily handle a large number of clients using the same WS application, I think that we could benefit from scaling outwards as well.

For instance, if a site wants multiple WS applications specified through different request URIs or through different Host headers (in the style of web server Virtual Hosts), then as it stands, all code is loaded into a single instance, and connection-based routing to the correct appliance must happen on all network events.

Additionally, as currently implemented, the application blocks until it receives a network event.  If, for example, data in a database that should be sent to all clients gets updated from outside of our application, then we would have to wait until a client sends a message to the server before the server can then unblock, check state, then update all clients.

Further, there's no support for multiple servers, such as clustered environments or environments replicated across regional data centers.  Granted, this is a fringe feature, but one that I believe is possible and should be a reasonable goal.

And, while this "bug" doesn't exist in the vanilla implementation (it's far too simple for this bug to even exist simply because the "process()" method is abstract), it's easy for bugs to be introduced to have user information bleed over between connections.  I want to avoid this, and make such bugs harder to be introduced.

However, I'm not the only user on this project any more, and my plans will break all current applications that have already implemented this WS server, requiring those applications to be rewritten if they attempt to upgrade.

I do plan on continuing to maintain the current version of this WS server through development of the new branch and for a reasonable time after the new version is released, but wouldn't be adding any new features (not like I had been adding any new features before, so nothing lost there).

So, this issue is one big happy feature request and architectural discussion thread.  Feel free to comment.

**Comment by merged-packets** [comment]
I like the idea of PHP websocket server. 
It greately simplifies the development of server applications.
But I would not overload the server itself with extra functions and dependencies which can make it heavier and more restrictive.
In my opinion, the server primary and disinctive function, apart from handling handshakes and control frames, should be encoding/decoding websocket messages and dispatching them down to apps.

Please, correct me if you think that I am wrong

**Comment by merged-packets** [comment]
From this perpective, current single-threaded design is very optimal. 
If developers want to isolate their apps and run them in separate processes or threads, they can do it in the process() handler using any interface or protocol of their choice.
This also gives them freedom to optimize performance, memory footprint and other important things they care about.
For this reason it would make sense to allow each user (client socket) to have custom process() handler matching the requested websocket extension.
Another thing that I would also add to the server is support for earlier websocket versions - some browsers build with Qt4 can only handle those.

**Comment by merged-packets** [comment]
Sending messages back to clients is more starightforward. Since socket writes are typically non-blocking, it would make sense to perform them directly in the caller context. This means that server doesn't need to run any sending threads and developer, if necessary, is free to use any threading model that meets the purpose. I hope this makes sense to anyone.

**Comment by merged-packets** [comment]
One capability that I would add to the server is support for earlier websocket versions - some browsers build with Qt4 can handle only those.

Another useful thing could be a PHP websocket client. This would allow the server connect to other websocket servers and use their apps.

**Comment by merged-packets** [comment]
One capability that I would add to the server is support for earlier websocket versions - some browsers build with Qt4 can handle only those.

Another useful thing could be a PHP websocket client. This would allow the server connect to other websocket servers and use their apps.

**Comment by amb3rl4nn** [comment]
The only thing I noticed immediately is the blocking for new connections and the while loop in the main run function.  I think adding an override for both of these would be two simple things that can be done quickly.  I'm running this library within my own server loop and other code is being executed when there is nothing to be done with websockets.  I've changed these both myself but I'm sure others might want an official implementation.

**Comment by Xaraknid** [comment]
First I would like to thank you for this awesome work.  Personally I like this version of ws because it's simple and small, around 616 lines of codes over 3 files and it do the work. And work on it's own did not rely on a patchwork of libraries like Ratchet requires React, Guzzle, and Symfony2's HttpFoundation in order to work.

About : 
-Multiple ws apps for multiple virtual host:  The easiest way should be to run multiple ws app each on different port.  In the event you want a single ws app to run several virtual host you'll need to keep track of host in users and when broadcast will only send on same host users for example.

-Data sent outside of apps and need to push to client : As Amb3rl4nn said the easy way will be to add an abstract function like process at the end of while(true) loop. All will depend on own everyone intend to use WS but I think in most use it will have a constant flow. And if not you can set a ping request in client with an interval that ping will unblock the select.

-Multiple server deserving the same host : I think too that should be an awesome feature and will help scalability. My personnal opinion about that as I think this multiple servers can be on different server in same region. Will be using a internal socket connection to a router server to communicate between server. Still at stage of idea.

-Process function can lead to "bug": I think I understand what "bug" you talk about as a bad manipulation from dev could lead of alteration of users data.  That is the job of dev to sanitize all data from client as "never thrust internet :)".

------

The current version need a revision over some little thing that will improve as blondie101010 said over security and stability : 

As written in RFC : 
-we should set a maximum payload size : this will prevent exhaustion of memory 
-maximum accepted fragmented payload ( continuous frame ) : this will prevent someone sending 10 000 frames of 1 bytes if we had a max_payload_size of 10K for example.

This 2 things depend on usage the dev do with WS so this 2 variables should be configurable.

Add a write_buffer : like read, write can write less than the length of the message we want to send and if this happens it's on the apps to deal with that as socket_write said I write X bytes, for the rest of message it's goes into the void.

Also set a maximum for write_buffer to prevent exaustion of memory leading to fatal.

With all this info we will be able to dynamically set a MAXIMUM CLIENT based on memory usage mem_pool_clients 66% of php memory available.

Max_clients = mem_pool_clients / ( max_buffer_write + max_buffer_read + internal_data_client )

Consider also that unless you tweak and recompile php there is a hard maximum of 1024 concurent connection while using socket_select().

**Comment by ghedipunk** [comment]
Current plans:

1) Fix bugs, security issues, implement TLS.
2) Experiment with better structured, more maintainable, more testable and loosely coupled code.
3) PHP-CPP. (Will still maintain both of the raw PHP versions but also have a compiled PHP extension for people who want/need screaming power.)

**Comment by ghedipunk** [comment]
Created a dev mailing list using Google Groups.  Anyone can read, anyone can _apply_ to join.  I will create a user mailing list some time in the future for more support related discussion in the future, but would like to keep bug and feature requests here on GitHub.  The dev mailing list will be for people who submit pull requests.

Mailing list is https://groups.google.com/forum/#!forum/gp-websockets-dev

Next immediate goal is a suite of unit tests.  The specifics aren't set yet, and anyone who had input is encouraged to drop by the mailing list.
As soon as we have some unit tests in place, I'm going to switch over to working on a project web site which will host a dogfood web chat to be further used in dev and support.
Finally, I'm still hard set on implementing TLS.  Other features, like accessing the user's PHP session, will be discussed further after TLS is implemented.
