### ISSUE TITLE
Script sleep at sending response to users

### ISSUE THREAD

**Issue by ASHKARAN** [ghedipunk/PHP-Websockets#20]
Hi thanks for your project !

I have a problem with this script, when my clients are more than 15-20 people server sleep at sending back message and  cant handle a lot messages.... and i don't know whats wrong with this !

![output](https://cloud.githubusercontent.com/assets/10007827/5427647/4ced90f0-83bc-11e4-8b1e-68b8da9a3b44.png)
![sourcecode](https://cloud.githubusercontent.com/assets/10007827/5427648/4cf33ec4-83bc-11e4-8910-c8375c8a9dc4.PNG)

**Comment by indulodha** [comment]
Hi, Just wanted to check if you got a solution for this. I have websockets which keep sleeping and start working after sometime.

Thanks for the help.

**Comment by vikashbbd** [comment]
I am also facing the same. Solutions please.

**Comment by ghedipunk** [comment]
Still open.  Will take another look this evening.

If anyone can come up with the most direct steps to reproduce by the time I'm able to look at this in greater detail (about 12 hours from now), I'd greatly appreciate it.

**Comment by vikashbbd** [comment]
I don't think there is any specific use case. I feel its just intermittent. May be something s blocking?

**Comment by Xaraknid** [comment]
I think @vikashbbd pinpoint it.  It's because socket are in blocking mode right now. That mean when sending message it's block untill the message was sent completely, do that for every socket client. Unnoticable if the message was sent in one or two packets. But you can see "sleeping" when your message was sent over several packets.

When socket are use in NON BLOCKING mode it's the job of application to check if the message was sent completely or not and buffer it to send it in next loop.

There is allready a working solution, but it's in developpement branch . Who still need some feature to meet the vision of @ghedipunk for the future of this project.

**Comment by ASHKARAN** [comment]
As a solution i'm using ratchet.
Ratchet is a PHP WEBSOCKET server which is using NON-BLOCKING system !
