### ISSUE TITLE
multiple instances of websocketserver

### ISSUE THREAD

**Issue by mortenko** [ghedipunk/PHP-Websockets#29]
Hi, 
I have question. Can I create multiple  instances of server like:
$server1=new server("127.0.0.2","9001");
$server1=new server("127.0.0.3","9002");
$server1=new server("127.0.0.4","9003");
and connect via web browsers to each server?
And also is it possible to connect via this web servers to mysql database ?

**Comment by Xaraknid** [comment]
Currently you can only load one server per app you run. If you load multiple intance of server in same app only one will respond.

If you run multiple app you will be able to connect on each server via web browsers.

you can connect to a dataside inside this app and send  info back to client like you do for php page via (apache,nginx,...).  But I did not recommend to use websocket to admin the database unless you use wss:// secure protocol same as https;//

**Comment by ghedipunk** [comment]
Closing:  This is questions, not bugs.

In order to have multiple instances of the server running, they have to be started as different processes.  (The `$port` parameter on `socket_bind()` only accepts one port... There is no way to specify a range of ports, and the server really isn't designed to ever allow multiple listening sockets.)

Also, yes, it is possible to connect to any database that you could otherwise connect to in any other PHP script.  This server has absolutely nothing to do with being able to connect to any database.

I'm a bit confused as to why it's even a question...  It's like saying "I can use my car to go to the store and buy milk.  If I use this truck instead, will that store still sell me milk?"

**Comment by mortenko** [comment]
If I use f.e. haproxy then I can get response from all three servers ?Sorry no connection to DB but  I mean  I can execute queries using this servers ?

**Comment by Xaraknid** [comment]
I'm not sure why you want multiple instance of server ?
As side note. The revision I working on will handle multiple virtualhost. So one instance of WS server will dispatch message accordingly. 

For DB question : you can do it the same way you do with SAPI environnement.

**Comment by mortenko** [comment]
Here is my problem http://stackoverflow.com/questions/29983805/executing-queries-using-haproxy-and-php-websocket

**Comment by Xaraknid** [comment]
I hope you understand php websocket is a blank sheet, a websocket server standalone that let you do what you want with it. See it to the foundation of what you will code.  In your case a bridge between client and DB server.

Each message send to websocket is processed by process() in testwebsock.php to let you do what you want with it.

Did websocket server recieve message to be processed.  To know that in function process($user,$message) from testwebsock.php add this line : 
```
$this->stdout($message);
```

And in your console you should see the message you'll need to process in your case sending the query to DB and maybe sending back to client some info.

**Comment by Xaraknid** [comment]
"Can php websocket communicate with DB? If you know some articles about it... Let me know."

Definately yes! I run both memcache and mysql with my websocket server.  Work perfectly!

Just to be sure you know. The core function you will use to process message from client is : process() from testwebsock.php.  If you want to know what exactly the message you receive add in process() this line : 

```
$this->stdout($message);
```
