### ISSUE TITLE
Warning: socket_bind(): unable to bind address [98]:

### ISSUE THREAD

**Issue by mohamedagamy** [ghedipunk/PHP-Websockets#73]
when I try to open testwebsock.php in my localhost in linux 
#!/usr/bin/env php 
Warning: socket_bind(): unable to bind address [98]: Address already in use in /var/www/html/websocket/websockets.php on line 23
Failed: socket_bind()

**Comment by ghedipunk** [comment]
Try changing the following line in testwebsock.php to have a different port number:

    $echo = new echoServer("0.0.0.0","9000");

9001 might be a good place to start.

Take a look at what ports are currently in use on your server if you don't want to just guess at which one might be open.

You'll also have to edit client.html with the updated port number.

Closing because this is not an issue with the library, it's a specific conflict with a server's configuration.  If you still need support, please feel free to continue the discussion.

**Comment by mohamedagamy** [comment]
Thank you Worked with me :+1:

**Comment by codem360** [comment]
PHP Warning:  socket_bind(): unable to bind address [99]: Cannot assign requested address in /var/www/html/websoc/websockets.php on line 23
Failed: socket_bind() 

I have find this issue on my aws server pls help me.
Thanks in advance.

**Comment by ghedipunk** [comment]
Please do not comment on closed threads with new errors.

Especially errors that show that you haven't done any basic troubleshooting
like running netstat to see what ports are already in use.

**Comment by git-TXX** [comment]
> PHP Warning: socket_bind(): unable to bind address [99]: Cannot assign requested address in /var/www/html/websoc/websockets.php on line 23
> Failed: socket_bind()
> 
> I have find this issue on my aws server pls help me.
> Thanks in advance.

check your real ip with command "ifconfig"
有可能因为当前所在的是内网，只能识别内网ip

**Comment by tiagoarrf** [comment]
> 

$address = 'localhost';

**Comment by tiagoarrf** [comment]
> PHP Warning: socket_bind(): unable to bind address [99]: Cannot assign requested address in /var/www/html/websoc/websockets.php on line 23 Failed: socket_bind()
> 
> I have find this issue on my aws server pls help me. Thanks in advance.

$address = 'localhost';

**Comment by ghedipunk** [comment]
Use 0.0.0.0. And read the PHP manual's entry on socket_bind().
