### ISSUE TITLE
Is php-websockets non blocking process?

### ISSUE THREAD

**Issue by pwFoo** [ghedipunk/PHP-Websockets#82]
I'm new with websocket and read about blocking and non blocking solutions... So my question...
Is php-websockets non-blocking or blocking solution?

**Comment by ghedipunk** [comment]
By default, it blocks waiting for new network traffic for up to 1 second per cycle.

There are ways to use a more interrupt driven event loop, such as by using LibEv in place of socket_select that currently drives the default event loop.  You can also make it a truly blocking system by removing the timeout.

Closing this because it isn't actually an issue, but if you have more questions, feel free to continue the conversation.
